import { Project } from "./types";
import { SPRITE_CATALOG } from "./catalog";

export const EXAMPLE_PROJECTS: { id: string; name: string; description: string; project: Project }[] = [
  {
    id: "ex_bouncing_robot",
    name: "🤖 Bouncing Robot Square",
    description: "Robot walks in a square and plays cheerful sound effects",
    project: {
      id: "ex_bouncing_robot",
      name: "Bouncing Robot Square",
      backdropUrl: "bg_blue_sky",
      gridVisible: true,
      sprites: [
        {
          id: "bot_1",
          name: "KMS Kite Bot",
          costumeUrl: SPRITE_CATALOG[0].svg,
          costumes: SPRITE_CATALOG[0].costumes,
          currentCostumeIndex: 0,
          x: -60,
          y: -60,
          rotation: 0,
          size: 100,
          visible: true,
          scripts: [
            {
              id: "h1",
              type: "when_flag_clicked",
              category: "events",
              inputs: {},
              x: 30,
              y: 30,
              next: {
                id: "s1",
                type: "say_text",
                category: "looks",
                inputs: { text: "Watch me walk in a square!" },
                next: {
                  id: "r1",
                  type: "repeat",
                  category: "control",
                  inputs: { times: 4 },
                  children: [
                    {
                      id: "m1",
                      type: "move_right",
                      category: "movement",
                      inputs: { steps: 50 },
                      next: {
                        id: "m2",
                        type: "move_down",
                        category: "movement",
                        inputs: { steps: 50 },
                        next: {
                          id: "snd1",
                          type: "play_sound",
                          category: "sound",
                          inputs: { sound: "pop" },
                        },
                      },
                    },
                  ],
                  next: {
                    id: "s2",
                    type: "say_text",
                    category: "looks",
                    inputs: { text: "Square Complete! 🎉" },
                  },
                },
              },
            },
          ],
        },
      ],
    },
  },
  {
    id: "ex_talking_friends",
    name: "💬 Talking Friends (Broadcast)",
    description: "Two sprites chatting using Broadcast events",
    project: {
      id: "ex_talking_friends",
      name: "Talking Friends",
      backdropUrl: "bg_classroom",
      gridVisible: true,
      sprites: [
        {
          id: "bot_a",
          name: "Leo the Boy",
          costumeUrl: SPRITE_CATALOG[4].svg,
          costumes: SPRITE_CATALOG[4].costumes,
          currentCostumeIndex: 0,
          x: -80,
          y: 20,
          rotation: 0,
          size: 90,
          visible: true,
          scripts: [
            {
              id: "h_a1",
              type: "when_flag_clicked",
              category: "events",
              inputs: {},
              x: 30,
              y: 30,
              next: {
                id: "s_a1",
                type: "say_text",
                category: "looks",
                inputs: { text: "Hi Maya! Want to code?" },
                next: {
                  id: "b_a1",
                  type: "broadcast",
                  category: "events",
                  inputs: { message: "greet" },
                },
              },
            },
          ],
        },
        {
          id: "bot_b",
          name: "Maya the Girl",
          costumeUrl: SPRITE_CATALOG[5].svg,
          costumes: SPRITE_CATALOG[5].costumes,
          currentCostumeIndex: 0,
          x: 80,
          y: 20,
          rotation: 0,
          size: 90,
          visible: true,
          scripts: [
            {
              id: "h_b1",
              type: "when_receive_message",
              category: "events",
              inputs: { message: "greet" },
              x: 30,
              y: 30,
              next: {
                id: "w_b1",
                type: "wait",
                category: "control",
                inputs: { seconds: 0.5 },
                next: {
                  id: "s_b1",
                  type: "say_text",
                  category: "looks",
                  inputs: { text: "Yes! Let's build a robot!" },
                  next: {
                    id: "snd_b1",
                    type: "play_sound",
                    category: "sound",
                    inputs: { sound: "cheer" },
                  },
                },
              },
            },
          ],
        },
      ],
    },
  },
  {
    id: "ex_keyboard_driver",
    name: "🎮 Keyboard Arrow Driver",
    description: "Control sprite movement with arrow keys",
    project: {
      id: "ex_keyboard_driver",
      name: "Keyboard Arrow Driver",
      backdropUrl: "bg_playground",
      gridVisible: true,
      sprites: [
        {
          id: "rover_1",
          name: "Wheeled Rover",
          costumeUrl: SPRITE_CATALOG[1].svg,
          costumes: SPRITE_CATALOG[1].costumes,
          currentCostumeIndex: 0,
          x: 0,
          y: 0,
          rotation: 0,
          size: 100,
          visible: true,
          scripts: [
            {
              id: "k_right",
              type: "when_key_pressed",
              category: "events",
              inputs: { key: "ArrowRight" },
              x: 30,
              y: 30,
              next: {
                id: "m_r",
                type: "move_right",
                category: "movement",
                inputs: { steps: 20 },
              },
            },
            {
              id: "k_left",
              type: "when_key_pressed",
              category: "events",
              inputs: { key: "ArrowLeft" },
              x: 30,
              y: 130,
              next: {
                id: "m_l",
                type: "move_left",
                category: "movement",
                inputs: { steps: 20 },
              },
            },
            {
              id: "k_up",
              type: "when_key_pressed",
              category: "events",
              inputs: { key: "ArrowUp" },
              x: 30,
              y: 230,
              next: {
                id: "m_u",
                type: "move_up",
                category: "movement",
                inputs: { steps: 20 },
              },
            },
            {
              id: "k_down",
              type: "when_key_pressed",
              category: "events",
              inputs: { key: "ArrowDown" },
              x: 30,
              y: 330,
              next: {
                id: "m_d",
                type: "move_down",
                category: "movement",
                inputs: { steps: 20 },
              },
            },
          ],
        },
      ],
    },
  },
];
