export type SupportedLanguage = 'en' | 'hi' | 'ta' | 'mr' | 'te' | 'bn';

export interface LanguageOption {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
];

export const UI_TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    heroTitle: 'STEM LENS & KINETIC CANVAS',
    heroSubtitle: 'A Unified AI, Robotics, IoT & Coding Learning Platform for Grades 3–12',
    stemLensTab: 'STEM Lens (AI Scanner)',
    kineticCanvasTab: 'Kinetic Canvas (Code & Simulate)',
    lmsTab: 'LMS & Compliance Portal',
    scanObject: 'Scan STEM Hardware',
    arOverlay: 'AR Circuit Overlay',
    doubtSolver: 'AI Doubt Solver',
    gradeSelect: 'Select Grade Band',
    exploreMode: 'Explore Library',
    buildInCanvas: 'Build this in Kinetic Canvas 🚀',
    blockCoding: 'Visual Block Coding',
    pythonCode: 'Python Code',
    cppCode: 'Arduino C++',
    runSimulation: 'Start Simulation',
    stopSimulation: 'Pause Simulation',
    deployHardware: 'One-Click Flash Hardware ⚡',
    aiCopilot: 'AI Co-Pilot Assistant',
  },
  hi: {
    heroTitle: 'स्टेम लेंस और काइनेटिक कैनवास',
    heroSubtitle: 'कक्षा 3-12 के लिए एआई, रोबोटिक्स, आईओटी और कोडिंग लर्निंग प्लेटफॉर्म',
    stemLensTab: 'स्टेम लेंस (एआई स्कैनर)',
    kineticCanvasTab: 'काइनेटिक कैनवास (कोड और सिमुलेशन)',
    lmsTab: 'एलएमएस और रिपोर्टिंग पोर्टल',
    scanObject: 'स्कैन स्टेम हार्डवेयर',
    arOverlay: 'एआर सर्किट ओवरले',
    doubtSolver: 'एआई शंका समाधान',
    gradeSelect: 'कक्षा श्रेणी चुनें',
    exploreMode: 'एक्सप्लोर लाइब्रेरी',
    buildInCanvas: 'इसे काइनेटिक कैनवास में बनाएं 🚀',
    blockCoding: 'विजुअल ब्लॉक कोडिंग',
    pythonCode: 'पायथन कोड',
    cppCode: 'ऑर्डिनो सी++',
    runSimulation: 'सिमुलेशन शुरू करें',
    stopSimulation: 'सिमुलेशन रोकें',
    deployHardware: 'हार्डवेयर में कोड भेजें ⚡',
    aiCopilot: 'एआई सह-पायलट सहायक',
  },
  ta: {
    heroTitle: 'ஸ்டெம் லென்ஸ் & கைனடிக் கேன்வாஸ்',
    heroSubtitle: 'வகுப்புகள் 3-12க்கான ஏஐ, ரோபோடிக்ஸ், ஐஓடி & கோடிங் கற்றல் தளம்',
    stemLensTab: 'ஸ்டெம் லென்ஸ் (ஏஐ ஸ்கேனர்)',
    kineticCanvasTab: 'கைனடிக் கேன்வாஸ் (கோட் & சிமுலேட்)',
    lmsTab: 'எல்எம்எஸ் & அறிக்கை போர்டல்',
    scanObject: 'ஹார்டுவேர் ஸ்கேன் செய்',
    arOverlay: 'ஏஆர் சர்க்யூட் மேலடுக்கு',
    doubtSolver: 'ஏஐ சந்தேகம் தீர்க்கும் அரட்டை',
    gradeSelect: 'வகுப்பைத் தேர்ந்தெடு',
    exploreMode: 'நூலகத்தை ஆராய்',
    buildInCanvas: 'கைனடிக் கேன்வாஸில் உருவாக்கு 🚀',
    blockCoding: 'விஷுவல் பிளாக் கோடிங்',
    pythonCode: 'பைதான் கோட்',
    cppCode: 'ஆர்டுயினோ சி++',
    runSimulation: 'சிமுலேஷனைத் தொடங்கு',
    stopSimulation: 'சிமுலேஷனை நிறுத்து',
    deployHardware: 'ஹார்டுவேருக்கு அனுப்பு ⚡',
    aiCopilot: 'ஏஐ கோ-பைலட் உதவியாளர்',
  },
  mr: {
    heroTitle: 'स्टेम लेन्स आणि कायनेटिक कॅनव्हास',
    heroSubtitle: 'इयत्ता ३-१२ साठी एआय, रोबोटिक्स, आयओटी आणि कोडिंग प्लॅटफॉर्म',
    stemLensTab: 'स्टेम लेन्स (एआय स्कॅनर)',
    kineticCanvasTab: 'कायनेटिक कॅनव्हास (कोड आणि सिम्युलेशन)',
    lmsTab: 'एलएमएस पोर्टल',
    scanObject: 'हार्डवेअर स्कॅन करा',
    arOverlay: 'एआर सर्किट ओव्हरले',
    doubtSolver: 'एआय शंका निवारण',
    gradeSelect: 'इयत्ता निवडा',
    exploreMode: 'एक्सप्लोर लायब्ररी',
    buildInCanvas: 'कायनेटिक कॅनव्हासमध्ये बनवा 🚀',
    blockCoding: 'ब्लॉक कोडिंग',
    pythonCode: 'पायथन कोड',
    cppCode: 'आर्डीनो सी++',
    runSimulation: 'सिम्युलेशन सुरू करा',
    stopSimulation: 'सिम्युलेशन थांबवा',
    deployHardware: 'हार्डवेअरवर फ्लॅश करा ⚡',
    aiCopilot: 'एआय को-पायलट',
  },
  te: {
    heroTitle: 'స్టెమ్ లెన్స్ & కైనెటిక్ కాన్వాస్',
    heroSubtitle: 'తరగతులు 3–12 విద్యార్థుల కోసం AI, రోబోటిక్స్ & కోడింగ్ ప్లాట్‌ఫారమ్',
    stemLensTab: 'స్టెమ్ లెన్స్ (AI స్కేనర్)',
    kineticCanvasTab: 'కైనెటిక్ కాన్వాస్ (కోడింగ్ & సిమ్యులేషన్)',
    lmsTab: 'LMS పోర్టల్',
    scanObject: 'హార్డ్‌వేర్ స్కాన్ చేయండి',
    arOverlay: 'AR సర్క్యూట్ ఓవర్లే',
    doubtSolver: 'AI సందేహాల నివృత్తి',
    gradeSelect: 'తరగతిని ఎంచుకోండి',
    exploreMode: 'లైబ్రరీని చూడండి',
    buildInCanvas: 'కైనెటిక్ కాన్వాస్‌లో నిర్మించండి 🚀',
    blockCoding: 'బ్లాక్ కోడింగ్',
    pythonCode: 'పైథాన్ కోడ్',
    cppCode: 'ఆర్డుయినో C++',
    runSimulation: 'సిమ్యులేషన్ ప్రారంభించండి',
    stopSimulation: 'సిమ్యులేషన్ ఆపండి',
    deployHardware: 'హార్డ్‌వేర్‌కి అప్‌లోడ్ చేయండి ⚡',
    aiCopilot: 'AI కో-పైలట్',
  },
  bn: {
    heroTitle: 'স্টেম লেন্স এবং কাইনেটিক ক্যানভাস',
    heroSubtitle: '৩-১২ শ্রেণির জন্য এআই, রোবোটিক্স, আইওটি ও কোডিং লার্নিং প্ল্যাটফর্ম',
    stemLensTab: 'স্টেম লেন্স (এআই স্ক্যানার)',
    kineticCanvasTab: 'কাইনেটিক ক্যানভাস (কোড ও সিমুলেশন)',
    lmsTab: 'এলএমএস এবং পোর্টাল',
    scanObject: 'হার্ডওয়্যার স্ক্যান করুন',
    arOverlay: 'এআর সার্কিট ওভারলে',
    doubtSolver: 'এআই প্রশ্ন সমাধান',
    gradeSelect: 'শ্রেণি নির্বাচন করুন',
    exploreMode: 'লাইব্রেরি এক্সপ্লোর করুন',
    buildInCanvas: 'কাইনেটিক ক্যানভাসে তৈরি করুন 🚀',
    blockCoding: 'ব্লক কোডিং',
    pythonCode: 'পাইথন কোড',
    cppCode: 'আরডুইনো সি++',
    runSimulation: 'সিমুলেশন শুরু করুন',
    stopSimulation: 'সিমুলেশন থামান',
    deployHardware: 'হার্ডওয়্যারে ফ্ল্যাশ করুন ⚡',
    aiCopilot: 'এআই কো-পাইলট সহকারী',
  }
};
